### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by hiddewie** [hiddewie/map-it#1]
A Dockerfile makes the README instructions less useful. Environment variables can be used to set the area and data.
A volume can be mounted to persist data.

**Comment by bertt** [comment]
I've made a start with running from docker see https://github.com/bertt/map-it/tree/dockerizing (contains so far only download.sh). Download.sh has some small changes to make it work.

To be run with '$ docker-compose up --build'

**Comment by hiddewie** [comment]
@bertt Thanks! Looks like a good start. I've also made some progress on making the map generation Dockerfile based on an old Debian version. I will merge some of your changes into the import Dockerfile!

Unfortunately I cannot get the mapnik-python bindings to work with Mapnik 3 and its Python bindings. By the documentation it seems a lot of manual compilation is needed and no binary packages are supplied.
