### ISSUE TITLE
generate.py: no such file or directory

### ISSUE THREAD

**Issue by bertt** [hiddewie/map-it#24]
When running hiddewie/map-it I get an error about /generate.py:

```
$ docker run -ti \
  --rm \
  -v $(pwd)/data:/map-it \
  --link postgres-osm:postgres-osm \
  -e PG_HOST=postgres-osm \
  -e PG_PORT=5432 \
  -e PG_USER="osm" \
  -e PG_PASSWORD="" \
  -e PG_DATABASE="gis" \
  -e MAP_NAME="map" \
  -e LATITUDES="N52" \
  -e LONGITUDES="E006" \
  -e TOP_LEFT_X="735324" \
  -e TOP_LEFT_Y="6874058" \
  -e OFFSET_PAGES_X="0" \
  -e OFFSET_PAGES_Y="0" \
  -e PAGES_HORIZONTAL="1" \
  -e PAGES_VERTICAL="1" \
  hiddewie/map-it

/usr/bin/python: can't open file './generate.py': [Errno 2] No such file or directory
```

**Comment by hiddewie** [comment]
@bartt the project directory needs to be linked into the container, not the data directory. That should solve the problem.

Setting the project directory in a constant would let you copy paste the commands.

**Comment by bertt** [comment]
yes that fixed it :-)

Now got one more error (must i set OUTPUT_PATH?): 

```
Rendering PDF
Traceback (most recent call last):
  File "./generate.py", line 756, in <module>
    renderMap(m, name)
  File "./generate.py", line 686, in renderMap
    pdf_surface = cairo.PDFSurface(OUTPUT_PATH + name + '.pdf', m.width, m.height)
IOError: error while writing to output stream
```

**Comment by bertt** [comment]
that error is fixed by creating an empty folder 'output'

**Comment by hiddewie** [comment]
Ah yes, the script should generate the output directory of course.

**Comment by bertt** [comment]
a suggestion: copy the generate.py script (+data) in the image, so it can run from anywhere

**Comment by hiddewie** [comment]
@bertt Yes, that would be possible. But when editing the Python script, the Docker image would have to be rebuilt every time the file changes.

I added the creation of the output directory if it does not exist yet.
