### ISSUE TITLE
Cannot guess driver for format shade

### ISSUE THREAD

**Issue by bertt** [hiddewie/map-it#3]
Hi, got an error while doing gdaldem hillshade:

$ gdaldem hillshade N48E018.hgt N48E018.shade
ERROR 1: Cannot guess driver for N48E018.shade

I think it's related to the gdal version installed, checked with 'gdalinfo --version', 
when version 1 is installed above command works, when version 2 is installed it gives the driver error.

In the docs I see conversion to .tif or .png format commonly used.

**Comment by hiddewie** [comment]
@bertt Thanks for the issue. I do not have a gdal version 2 available for testing (working on that with Docker images). 

I added a PR (partly taken from your Dockerfile) which should solve the issue. Can you confirm?
